In [1]:
import gym
import numpy as np
import random
import time

In [2]:
from tqdm import tqdm_notebook as tqdm

In [3]:
env = gym.make('FrozenLake-v0')

https://github.com/MR901/Reinforcement-Learninng/blob/2fa526c6d8b1b49a7e430ede85f1ba5d2830a755/bin/Dis_Dis_FrozenLake-Custom.ipynb

In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


## Generating ann empty q_Table
actionSpaceSize = env.action_space.n
stateSpaceSize = env.observation_space.n
q_table = np.zeros((stateSpaceSize, actionSpaceSize))

# Print initial Q-table
print("\n\n*** Initial Q-table ***\n")
print(q_table)


# Q-learning algorithm
rewardsAllEpisodes_li = []
for episode in tqdm(range(num_episodes)):
    # initialize new episode params
    state = env.reset()
    done = False
    rewardsCurrentEpisode = 0
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        
        # Take new action
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        # Set new state
        state = new_state
        
        # Add new reward
        rewardsCurrentEpisode += reward 
        
        if done == True: 
            break
        
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    # Add current episode reward to total rewards list
    rewardsAllEpisodes_li.append(rewardsCurrentEpisode)


# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewardsAllEpisodes_li),num_episodes/1000)
count = 1000


print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



*** Initial Q-table ***

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

********Average reward per thousand episodes********

1000 :  0.059000000000000045
2000 :  0.19200000000000014
3000 :  0.4000000000000003
4000 :  0.5680000000000004
5000 :  0.6220000000000004
6000 :  0.6630000000000005
7000 :  0.6960000000000005
8000 :  0.7080000000000005
9000 :  0.6650000000000005
10000 :  0.6400000000000005


********Q-table********

[[0.54963982 0.4884794  0.48098438 0.49054504]
 [0.32615292 0.22521553 0.27790162 0.48957833]
 [0.37637315 0.36622792 0.3934112  0.45747242]
 [0.27383803 0.2770258  0.29984251 0.41719784]
 [0.56979876 0.3489775  0.26710695 0.30613877]
 [0.         0.         0.         0.        ]
 [0.29946924 0.14002676 0.13103977 0.09913199]
 [0.         0.         0.         0.        ]
